<?php

/** 
 * return @options array
 */
function islandora_journal_sp_country_options() {
	$country_list = countries_api_list();
	foreach ($country_list as $row) {
		$options[$row['iso3']] = $row['printable_name'];
	}
	return $options;
}

/**
 * return @objects array
 */
function islandora_journal_sp_required_fedora_objects() {

  $module_path = drupal_get_path('module','islandora_journal_sp');
  
  return array(
    'islandora_journal_sp' => array(
      'module' => 'islandora_journal_sp',
      'title' => 'Islandora Journal Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:journalCModel',
          'dsid' => 'ISLANDORACM',
          'label' => 'Islandora Journal Content Model',
          'cmodel' => 'fedora-system:CModel-3.0',
          'datastream_file' => "$module_path/xml/JOURNAL_SP_CMODEL.xml",
        ),
        array(
          'pid' => 'islandora:journalCollection',
          'label' => 'Islandora Journal Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_mimetype_document.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/JOURNAL_COLLECTIONPOLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
  
}
